//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFinanceEntities : DbContext
    {
        public dbFinanceEntities()
            : base("name=dbFinanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblFirstLevel> tblFirstLevels { get; set; }
        public virtual DbSet<tblFourthLevelAccount> tblFourthLevelAccounts { get; set; }
        public virtual DbSet<tblSecondLevel> tblSecondLevels { get; set; }
        public virtual DbSet<tblThirdLevel> tblThirdLevels { get; set; }
        public virtual DbSet<tblVoucher> tblVouchers { get; set; }
        public virtual DbSet<tblVoucherDetail> tblVoucherDetails { get; set; }
        public virtual DbSet<tblVoucherDetailTemp> tblVoucherDetailTemps { get; set; }
        public virtual DbSet<tblVoucherTemp> tblVoucherTemps { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vSecondLevel> vSecondLevels { get; set; }
    }
}
