//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblFirstLevel
    {
        public List<tblFirstLevel> FirstLevelDetails { get; set; }
        //AppDbEntities db = new AppDbEntities();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFirstLevel()
        {
            this.tblSecondLevels = new HashSet<tblSecondLevel>();
        }

        public int firstLevelId { get; set; }

        [Display(Name = "First Level Account:")]
        [Required(ErrorMessage = "Field required!")]
        public string firstLevelAccount { get; set; }

        [Display(Name = "Description:")]
        public string firstLevelDesc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSecondLevel> tblSecondLevels { get; set; }
    
    }
}
