//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFourthLevelAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFourthLevelAccount()
        {
            this.tblVoucherDetails = new HashSet<tblVoucherDetail>();
            this.tblVoucherDetailTemps = new HashSet<tblVoucherDetailTemp>();
        }
    
        public int accountId { get; set; }
        public string accountCode { get; set; }
        public Nullable<int> accountNo { get; set; }
        public string accountTitle { get; set; }
        public int thirdLevelId { get; set; }
        public string mobileNo { get; set; }
        public string email { get; set; }
        public Nullable<int> cityId { get; set; }
        public string address { get; set; }
        public Nullable<decimal> taxPercent { get; set; }
        public Nullable<int> chequeNoStart { get; set; }
        public Nullable<int> chequeNoEnd { get; set; }
    
        public virtual tblThirdLevel tblThirdLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherDetail> tblVoucherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherDetailTemp> tblVoucherDetailTemps { get; set; }
    }
}
