//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSecondLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSecondLevel()
        {
            this.tblThirdLevels = new HashSet<tblThirdLevel>();
        }
        public List<tblSecondLevel> SecLevelDetails { get; set; } 

        public List<string> SecLevelDetail  = new List<string>(5);

        public int secondLevelId { get; set; }
        [Display(Name = "Second Level:")]
        [Required(ErrorMessage = "Field required!")]
        public string secondLevelAccount { get; set; }

        [Display(Name = "First Level :")]
        [Required(ErrorMessage = "Field required!")]
        public int firstLevelId { get; set; }
        [Display(Name = "Description:")]
        public string secondLevelDesc { get; set; }
    
        public virtual tblFirstLevel tblFirstLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblThirdLevel> tblThirdLevels { get; set; }
    }
    
 
}
