//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThirdLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblThirdLevel()
        {
            this.tblFourthLevelAccounts = new HashSet<tblFourthLevelAccount>();
        }
    
        public int thirdLevelId { get; set; }
        public string thirdLevelAccount { get; set; }
        public int secondLevelId { get; set; }
        public string thirdLevelDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFourthLevelAccount> tblFourthLevelAccounts { get; set; }
        public virtual tblSecondLevel tblSecondLevel { get; set; }
    }
}
