//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVoucherTemp()
        {
            this.tblVoucherDetailTemps = new HashSet<tblVoucherDetailTemp>();
        }
    
        public int voucherId { get; set; }
        public Nullable<int> voucherNo { get; set; }
        public string voucherCode { get; set; }
        public Nullable<System.DateTime> voucherDate { get; set; }
        public string voucherType { get; set; }
        public string paymentMode { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public Nullable<int> userIdUpdate { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public Nullable<int> isApprove { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoucherDetailTemp> tblVoucherDetailTemps { get; set; }
    }
}
