//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherDetailTemp
    {
        public int voucherDetailId { get; set; }
        public int voucherId { get; set; }
        public string description { get; set; }
        public decimal debitAmount { get; set; }
        public decimal creditAmount { get; set; }
        public Nullable<int> chequeNo { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public int accountId { get; set; }
    
        public virtual tblFourthLevelAccount tblFourthLevelAccount { get; set; }
        public virtual tblVoucherTemp tblVoucherTemp { get; set; }
    }
}
