//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSecondLevel
    {
        public List<vSecondLevel> SecLevelDetails { get; set; }

        public int firstLevelId { get; set; }
        public string firstLevelAccount { get; set; }
        public int secondLevelId { get; set; }
        public string secondLevelAccount { get; set; }
        public string secondLevelDesc { get; set; }
    }
}
